import { StyleSheet } from 'react-native';

export const composerStyles = StyleSheet.create({
  composer: {
    width: '100%',
    borderRadius: 29,
    overflow: 'hidden',
    // 输入框只保留一块完整表面，不再叠加描边、阴影和内部按钮底板。
  },
  slashPalette: { maxHeight: 264, borderBottomWidth: StyleSheet.hairlineWidth, borderTopLeftRadius: 22, borderTopRightRadius: 22, overflow: 'hidden' },
  slashPaletteScroll: { maxHeight: 264 },
  mentionPaletteLabel: { paddingHorizontal: 12, paddingTop: 9, paddingBottom: 3, fontSize: 11, fontWeight: '700' },
  mentionLogo: { width: 32, height: 32, borderRadius: 9 },
  mentionLogoFallback: { width: 32, height: 32, borderRadius: 9, alignItems: 'center', justifyContent: 'center' },
  mentionLogoText: { fontSize: 10, fontWeight: '800' },
  mentionKindBadge: { borderRadius: 10, paddingHorizontal: 7, paddingVertical: 3 },
  mentionKindText: { fontSize: 9.5, fontWeight: '800' },
  slashCommandRow: { minHeight: 58, flexDirection: 'row', alignItems: 'center', gap: 10, paddingHorizontal: 11, paddingVertical: 8 },
  slashCommandIcon: { width: 32, height: 32, borderRadius: 10, alignItems: 'center', justifyContent: 'center' },
  slashCommandIconText: { fontSize: 17, fontWeight: '700' },
  slashCommandBody: { minWidth: 0, flex: 1, gap: 2 },
  slashCommandTitleRow: { minWidth: 0, flexDirection: 'row', alignItems: 'center', gap: 7 },
  slashCommandName: { fontSize: 13, fontWeight: '600' },
  slashCommandHint: { minWidth: 0, flexShrink: 1, fontSize: 11 },
  slashCommandDescription: { fontSize: 11.5, lineHeight: 16 },
  queuedPromptList: { gap: 5, borderBottomWidth: StyleSheet.hairlineWidth, paddingHorizontal: 10, paddingTop: 8, paddingBottom: 7 },
  queuedPromptLabel: { paddingHorizontal: 2, fontSize: 10, fontWeight: '600' },
  queuedPromptRow: { minHeight: 30, borderRadius: 10, flexDirection: 'row', alignItems: 'center', gap: 5, paddingLeft: 9, paddingRight: 4 },
  queuedPromptText: { minWidth: 0, flex: 1, fontSize: 11.5 },
  queuedPromptCount: { fontSize: 10, fontVariant: ['tabular-nums'] },
  queuedPromptRemove: { width: 28, height: 28, alignItems: 'center', justifyContent: 'center' },
  composerQuote: { borderBottomWidth: StyleSheet.hairlineWidth, paddingHorizontal: 12, paddingVertical: 9, flexDirection: 'row', alignItems: 'flex-start', gap: 8 },
  composerQuoteBody: { minWidth: 0, flex: 1 },
  composerQuoteLabel: { fontSize: 10.5, fontWeight: '700' },
  composerQuoteText: { marginTop: 2, fontSize: 11.5, lineHeight: 16 },
  composerQuoteClose: { width: 28, height: 28, alignItems: 'center', justifyContent: 'center', marginTop: -3, marginRight: -4 },
  attachmentList: { gap: 8, paddingHorizontal: 10, paddingTop: 10, paddingBottom: 2 },
  attachmentChip: { width: 188, minHeight: 52, borderWidth: StyleSheet.hairlineWidth, borderRadius: 12, padding: 5, flexDirection: 'row', alignItems: 'center', gap: 7 },
  attachmentThumb: { width: 42, height: 42, borderRadius: 8 },
  attachmentFileIcon: { width: 42, height: 42, borderRadius: 8, alignItems: 'center', justifyContent: 'center' },
  attachmentLabelArea: { minWidth: 0, flex: 1 },
  attachmentName: { fontSize: 12, fontWeight: '600' },
  attachmentStatus: { marginTop: 2, fontSize: 10 },
  attachmentError: { paddingHorizontal: 14, paddingTop: 7, fontSize: 11, lineHeight: 15 },
  composerInput: { flex: 1, minWidth: 0, minHeight: 44, maxHeight: 140, paddingHorizontal: 2, paddingTop: 10, paddingBottom: 10, fontSize: 17, lineHeight: 24 },
  inputRow: { minHeight: 58, flexDirection: 'row', alignItems: 'flex-end', gap: 4, padding: 7 },
  roundIconButton: { width: 44, height: 44, borderRadius: 22, alignItems: 'center', justifyContent: 'center' },
  sendButton: { width: 44, height: 44, borderRadius: 22, alignItems: 'center', justifyContent: 'center' },
  sendButtonDisabled: { opacity: 0.4 },
});
