import { StyleSheet } from 'react-native';

export const composerStyles = StyleSheet.create({
  composer: {
    width: '100%',
    borderWidth: StyleSheet.hairlineWidth,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 3,
  },
  composerHero: { minHeight: 118, borderRadius: 24, paddingTop: 4 },
  composerThread: { minHeight: 82, borderRadius: 22, paddingTop: 2 },
  slashPalette: { maxHeight: 264, borderBottomWidth: StyleSheet.hairlineWidth, borderTopLeftRadius: 22, borderTopRightRadius: 22, overflow: 'hidden' },
  slashPaletteScroll: { maxHeight: 264 },
  mentionPaletteLabel: { paddingHorizontal: 12, paddingTop: 9, paddingBottom: 3, fontSize: 11, fontWeight: '700' },
  mentionLogo: { width: 32, height: 32, borderRadius: 9 },
  mentionLogoFallback: { width: 32, height: 32, borderRadius: 9, alignItems: 'center', justifyContent: 'center' },
  mentionLogoText: { fontSize: 10, fontWeight: '800' },
  mentionKindBadge: { borderRadius: 10, paddingHorizontal: 7, paddingVertical: 3 },
  mentionKindText: { fontSize: 9.5, fontWeight: '800' },
  slashCommandRow: { minHeight: 58, flexDirection: 'row', alignItems: 'center', gap: 10, paddingHorizontal: 11, paddingVertical: 8 },
  slashCommandIcon: { width: 32, height: 32, borderRadius: 10, alignItems: 'center', justifyContent: 'center' },
  slashCommandIconText: { fontSize: 17, fontWeight: '700' },
  slashCommandBody: { minWidth: 0, flex: 1, gap: 2 },
  slashCommandTitleRow: { minWidth: 0, flexDirection: 'row', alignItems: 'center', gap: 7 },
  slashCommandName: { fontSize: 13, fontWeight: '600' },
  slashCommandHint: { minWidth: 0, flexShrink: 1, fontSize: 11 },
  slashCommandDescription: { fontSize: 11.5, lineHeight: 16 },
  queuedPromptList: { gap: 5, borderBottomWidth: StyleSheet.hairlineWidth, paddingHorizontal: 10, paddingTop: 8, paddingBottom: 7 },
  queuedPromptLabel: { paddingHorizontal: 2, fontSize: 10, fontWeight: '600' },
  queuedPromptRow: { minHeight: 30, borderRadius: 10, flexDirection: 'row', alignItems: 'center', gap: 5, paddingLeft: 9, paddingRight: 4 },
  queuedPromptText: { minWidth: 0, flex: 1, fontSize: 11.5 },
  queuedPromptCount: { fontSize: 10, fontVariant: ['tabular-nums'] },
  queuedPromptRemove: { width: 28, height: 28, alignItems: 'center', justifyContent: 'center' },
  composerQuote: { borderBottomWidth: StyleSheet.hairlineWidth, paddingHorizontal: 12, paddingVertical: 9, flexDirection: 'row', alignItems: 'flex-start', gap: 8 },
  composerQuoteBody: { minWidth: 0, flex: 1 },
  composerQuoteLabel: { fontSize: 10.5, fontWeight: '700' },
  composerQuoteText: { marginTop: 2, fontSize: 11.5, lineHeight: 16 },
  composerQuoteClose: { width: 28, height: 28, alignItems: 'center', justifyContent: 'center', marginTop: -3, marginRight: -4 },
  attachmentList: { gap: 8, paddingHorizontal: 10, paddingTop: 10, paddingBottom: 2 },
  attachmentChip: { width: 188, minHeight: 52, borderWidth: StyleSheet.hairlineWidth, borderRadius: 12, padding: 5, flexDirection: 'row', alignItems: 'center', gap: 7 },
  attachmentThumb: { width: 42, height: 42, borderRadius: 8 },
  attachmentFileIcon: { width: 42, height: 42, borderRadius: 8, alignItems: 'center', justifyContent: 'center' },
  attachmentLabelArea: { minWidth: 0, flex: 1 },
  attachmentName: { fontSize: 12, fontWeight: '600' },
  attachmentStatus: { marginTop: 2, fontSize: 10 },
  attachmentError: { paddingHorizontal: 14, paddingTop: 7, fontSize: 11, lineHeight: 15 },
  voiceError: { paddingHorizontal: 14, paddingTop: 7, fontSize: 11, lineHeight: 15 },
  composerInput: { minHeight: 40, maxHeight: 145, paddingHorizontal: 15, paddingTop: 12, paddingBottom: 5, fontSize: 16, lineHeight: 22 },
  composerInputHero: { minHeight: 62, paddingHorizontal: 17, paddingTop: 16 },
  composerToolbar: { minHeight: 43, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 8, paddingBottom: 7 },
  composerToolbarLeft: { minWidth: 0, flex: 1, flexDirection: 'row', alignItems: 'center', gap: 5 },
  composerToolbarRight: { flexDirection: 'row', alignItems: 'center', gap: 5 },
  roundIconButton: { width: 33, height: 33, borderRadius: 17, alignItems: 'center', justifyContent: 'center' },
  modelBadge: { minWidth: 0, maxWidth: 180, height: 29, flexDirection: 'row', alignItems: 'center', gap: 5, borderRadius: 15, paddingHorizontal: 10 },
  modelText: { minWidth: 0, flexShrink: 1, fontSize: 11.5, fontWeight: '500' },
  voiceMeter: { minWidth: 0, flex: 1, height: 29, flexDirection: 'row', alignItems: 'center', gap: 8, paddingHorizontal: 4 },
  voiceWaveform: { minWidth: 0, flex: 1, height: 22, flexDirection: 'row', alignItems: 'center', gap: 2 },
  voiceWaveBar: { width: 2.5, borderRadius: 2 },
  voiceDuration: { width: 34, fontSize: 11, fontVariant: ['tabular-nums'], textAlign: 'right' },
  voiceRecordingButton: { backgroundColor: '#E5484D' },
  sendButton: { width: 34, height: 34, borderRadius: 17, alignItems: 'center', justifyContent: 'center' },
  sendButtonDisabled: { opacity: 0.24 },
});
