import { StyleSheet } from 'react-native';

export const skillsScreenStyles = StyleSheet.create({
  root: { flex: 1, paddingHorizontal: 16, paddingTop: 16 },
  summaryRow: { marginBottom: 22, gap: 6 },
  description: { maxWidth: 680, fontSize: 13, lineHeight: 20 },
  caption: { fontSize: 12, fontWeight: '600' },
  catalog: { flex: 1, borderRadius: 22, paddingHorizontal: 12, paddingTop: 12, overflow: 'hidden' },
  catalogHeader: { minHeight: 45, borderBottomWidth: StyleSheet.hairlineWidth, paddingHorizontal: 4, paddingBottom: 10, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  catalogTitle: { fontSize: 13, fontWeight: '700' },
  headerActions: { flexDirection: 'row', alignItems: 'center', gap: 5 },
  countBadge: { minWidth: 31, height: 25, borderRadius: 13, paddingHorizontal: 9, alignItems: 'center', justifyContent: 'center' },
  countText: { fontSize: 12, fontWeight: '600' },
  refreshButton: { width: 34, height: 34, borderRadius: 17, alignItems: 'center', justifyContent: 'center' },
  errorBanner: { marginTop: 10, borderRadius: 14, paddingHorizontal: 12, paddingVertical: 10, flexDirection: 'row', alignItems: 'center', gap: 10 },
  errorText: { flex: 1, fontSize: 12.5, lineHeight: 18 },
  retryText: { fontSize: 12.5, fontWeight: '700' },
  loadingState: { flex: 1, minHeight: 220, alignItems: 'center', justifyContent: 'center', gap: 9 },
  listContent: { paddingVertical: 9, paddingBottom: 20 },
  emptyContent: { flexGrow: 1, minHeight: 220, alignItems: 'center', justifyContent: 'center' },
  emptyText: { fontSize: 13 },
  skillRow: { minHeight: 84, borderBottomWidth: StyleSheet.hairlineWidth, borderRadius: 16, paddingHorizontal: 8, paddingVertical: 10, flexDirection: 'row', alignItems: 'center', gap: 11 },
  skillIcon: { width: 48, height: 48, borderRadius: 14, alignItems: 'center', justifyContent: 'center' },
  skillCopy: { flex: 1, minWidth: 0 },
  skillTitleRow: { flexDirection: 'row', alignItems: 'center', gap: 7 },
  skillTitle: { flexShrink: 1, fontSize: 15, lineHeight: 20, fontWeight: '700' },
  sourceBadge: { borderRadius: 9, paddingHorizontal: 7, paddingVertical: 3 },
  sourceText: { fontSize: 10, fontWeight: '700' },
  skillDescription: { marginTop: 3, fontSize: 13, lineHeight: 19 },
  unavailableReason: { marginTop: 2, fontSize: 11.5, lineHeight: 16 },
  statusBadge: { minHeight: 27, borderRadius: 14, paddingHorizontal: 8, flexDirection: 'row', alignItems: 'center', gap: 4 },
  statusText: { fontSize: 11, fontWeight: '700' },
  modalRoot: { flex: 1, flexDirection: 'row', justifyContent: 'flex-end' },
  modalBackdrop: { position: 'absolute', top: 0, right: 0, bottom: 0, left: 0, backgroundColor: 'rgba(0,0,0,0.24)' },
  detailPanel: { height: '100%', paddingHorizontal: 18, shadowColor: '#000', shadowOffset: { width: -8, height: 0 }, shadowOpacity: 0.14, shadowRadius: 24, elevation: 16 },
  detailTopBar: { minHeight: 62, flexDirection: 'row', alignItems: 'flex-start', gap: 11 },
  detailIcon: { width: 48, height: 48, borderRadius: 15, alignItems: 'center', justifyContent: 'center' },
  detailHeading: { flex: 1, minWidth: 0, paddingTop: 1 },
  detailTitle: { fontSize: 20, lineHeight: 27, fontWeight: '700' },
  detailBadges: { marginTop: 5, flexDirection: 'row', flexWrap: 'wrap', gap: 6 },
  closeButton: { width: 36, height: 36, borderRadius: 18, alignItems: 'center', justifyContent: 'center' },
  detailLoading: { marginTop: 28, flexDirection: 'row', alignItems: 'center', gap: 9 },
  detailLoadingText: { fontSize: 13 },
  detailError: { marginTop: 28, borderRadius: 16, paddingHorizontal: 12, paddingVertical: 12, gap: 10 },
  detailRetryButton: { alignSelf: 'flex-start', minHeight: 34, justifyContent: 'center' },
  detailContent: { paddingTop: 24, paddingBottom: 26, gap: 23 },
  detailSection: { gap: 8 },
  detailSectionTitle: { fontSize: 12, fontWeight: '600' },
  detailDescription: { fontSize: 14, lineHeight: 23 },
  metaGrid: { flexDirection: 'row', gap: 8 },
  metaItem: { flex: 1, minWidth: 0, borderRadius: 16, paddingHorizontal: 12, paddingVertical: 10 },
  metaLabel: { fontSize: 11 },
  metaValue: { marginTop: 2, fontSize: 13, fontWeight: '600' },
  unavailableDetail: { fontSize: 13, lineHeight: 20 },
  requirements: { gap: 13 },
  noRequirements: { fontSize: 13 },
  requirementLine: { gap: 7 },
  requirementTitleRow: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  requirementTitle: { fontSize: 12 },
  requirementPills: { flexDirection: 'row', flexWrap: 'wrap', gap: 6 },
  pill: { maxWidth: '100%', minHeight: 24, borderRadius: 12, paddingHorizontal: 9, alignItems: 'center', justifyContent: 'center' },
  pillText: { maxWidth: 260, fontSize: 11, fontWeight: '600' },
  rawBlock: { borderWidth: StyleSheet.hairlineWidth, borderRadius: 18, padding: 12 },
  rawHeader: { minHeight: 28, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  rawTitle: { fontSize: 13, fontWeight: '600' },
  rawContent: { marginTop: 10, maxHeight: 520, borderWidth: StyleSheet.hairlineWidth, borderRadius: 14, paddingHorizontal: 13, paddingVertical: 12 },
  rawText: { fontSize: 12, lineHeight: 20, fontFamily: process.env.EXPO_OS === 'ios' ? 'Menlo' : 'monospace' },
});
