import { StyleSheet } from 'react-native';

export const fileEditStyles = StyleSheet.create({
  fileGroup: { width: '100%', gap: 7, paddingVertical: 4 },
  fileCard: { width: '100%', overflow: 'hidden', borderWidth: StyleSheet.hairlineWidth, borderRadius: 10 },
  fileHeader: { minHeight: 54, paddingHorizontal: 9, paddingVertical: 8, flexDirection: 'row', alignItems: 'center', gap: 8 },
  fileStatusIcon: { width: 18, alignItems: 'center' },
  fileTitleArea: { minWidth: 0, flex: 1 },
  fileAction: { fontSize: 10.5, lineHeight: 14, fontWeight: '500' },
  filePath: { marginTop: 1, fontSize: 12.5, lineHeight: 17, fontWeight: '600' },
  fileError: { marginTop: 2, fontSize: 10.5, lineHeight: 14 },
  diffPair: { flexDirection: 'row', alignItems: 'center', gap: 5 },
  added: { color: '#2F8F61', fontSize: 11, fontVariant: ['tabular-nums'] },
  deleted: { color: '#C35A63', fontSize: 11, fontVariant: ['tabular-nums'] },
  diffToggle: {
    minHeight: 31,
    borderTopWidth: StyleSheet.hairlineWidth,
    paddingHorizontal: 9,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  diffToggleLabel: { minWidth: 0, flex: 1, fontSize: 10.5, lineHeight: 15, fontWeight: '600' },
  diffToggleCount: { fontSize: 10.5, lineHeight: 15, fontVariant: ['tabular-nums'] },
  diffPanel: { borderTopWidth: StyleSheet.hairlineWidth },
  diffTable: { minWidth: '100%', paddingVertical: 5 },
  diffHunk: { borderTopWidth: StyleSheet.hairlineWidth, marginTop: 4, paddingTop: 4 },
  diffGap: {
    minHeight: 25,
    paddingHorizontal: 8,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
  },
  diffGapBadge: {
    overflow: 'hidden',
    borderWidth: StyleSheet.hairlineWidth,
    borderRadius: 4,
    paddingHorizontal: 4,
    fontFamily: 'monospace',
    fontSize: 10,
    lineHeight: 15,
  },
  diffGapText: { fontSize: 10.5, lineHeight: 15 },
  diffRow: { minHeight: 20, flexDirection: 'row', alignItems: 'stretch' },
  diffLineNumber: {
    width: 39,
    borderRightWidth: StyleSheet.hairlineWidth,
    paddingHorizontal: 5,
    paddingVertical: 2,
    textAlign: 'right',
    fontFamily: 'monospace',
    fontSize: 9.5,
    lineHeight: 16,
    fontVariant: ['tabular-nums'],
  },
  diffMarker: {
    width: 21,
    paddingLeft: 7,
    paddingVertical: 2,
    fontFamily: 'monospace',
    fontSize: 10.5,
    lineHeight: 16,
  },
  diffCode: {
    minWidth: 280,
    paddingRight: 12,
    paddingVertical: 2,
    fontFamily: 'monospace',
    fontSize: 10.5,
    lineHeight: 16,
  },
  diffAdded: { backgroundColor: 'rgba(47,143,97,0.08)' },
  diffDeleted: { backgroundColor: 'rgba(195,90,99,0.08)' },
  diffMoreButton: {
    minHeight: 30,
    borderTopWidth: StyleSheet.hairlineWidth,
    paddingHorizontal: 9,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  moreLines: { fontSize: 10.5, lineHeight: 15, fontWeight: '600' },
  diffTruncated: {
    minHeight: 34,
    borderTopWidth: StyleSheet.hairlineWidth,
    paddingHorizontal: 9,
    paddingVertical: 6,
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: 7,
  },
  diffTruncatedText: { fontSize: 10.5, lineHeight: 15 },
  openFileButton: { flexDirection: 'row', alignItems: 'center', gap: 4, paddingVertical: 2 },
  openFileText: { fontSize: 10.5, lineHeight: 15, fontWeight: '600' },
});
