import { StyleSheet } from 'react-native';

import type { Palette } from '@/ui/palette';

/** 会话面板及其操作层共用主题，避免深色模式中残留旧侧栏的固定浅色。 */
export function createConversationStyles(colors: Palette) {
  return StyleSheet.create({
    keyboardRoot: { flex: 1 },
    modalRoot: { flex: 1, justifyContent: 'flex-end' },
    modalRootWide: { justifyContent: 'center', alignItems: 'center', padding: 24 },
    backdrop: { position: 'absolute', inset: 0, backgroundColor: 'rgba(10,18,24,0.32)' },
    sheet: {
      width: '100%', maxHeight: '100%', backgroundColor: colors.card, borderTopLeftRadius: 24,
      borderTopRightRadius: 24, overflow: 'hidden', boxShadow: '0 -8px 30px rgba(0,0,0,0.12)',
    },
    content: { flex: 1 },
    sheetWide: { maxWidth: 640, borderRadius: 24 },
    handle: { alignSelf: 'center', width: 34, height: 4, borderRadius: 3, backgroundColor: colors.border, marginTop: 10 },
    header: { flexDirection: 'row', alignItems: 'center', gap: 12, paddingHorizontal: 20, paddingVertical: 18, borderBottomWidth: 1, borderBottomColor: colors.border },
    logo: { width: 38, height: 38, borderRadius: 12 },
    heading: { flex: 1, minWidth: 0, gap: 3 },
    title: { color: colors.foreground, fontSize: 20, fontWeight: '700' },
    subtitle: { color: colors.muted, fontSize: 13 },
    closeButton: { width: 44, height: 44, borderRadius: 22, alignItems: 'center', justifyContent: 'center' },
    actions: { flexDirection: 'row', alignItems: 'center', gap: 10, padding: 20, paddingBottom: 14 },
    actionButton: { minHeight: 44, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 9, borderRadius: 14, paddingHorizontal: 14 },
    newChatButton: { flex: 1, backgroundColor: '#208AEF' },
    newChatLabel: { color: '#FFFFFF', fontSize: 15, fontWeight: '600' },
    utilityButton: { width: 44, borderWidth: 1, borderColor: colors.border, paddingHorizontal: 0 },
    actionLabel: { color: colors.foreground, fontSize: 14, fontWeight: '500' },
    rowPressed: { backgroundColor: colors.pressed },
    list: { flex: 1, minHeight: 0 },
    listHeading: { minHeight: 42, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 8, paddingHorizontal: 20 },
    listTitle: { color: colors.foreground, fontSize: 15, fontWeight: '600' },
    archivedToggle: { minHeight: 44, justifyContent: 'center', paddingHorizontal: 8, borderRadius: 12 },
    archivedText: { color: colors.muted, fontSize: 13, fontWeight: '500' },
    listContent: { paddingHorizontal: 12, paddingBottom: 14 },
    projectsTitle: { paddingHorizontal: 12, paddingTop: 10, paddingBottom: 6, color: colors.muted, fontSize: 12, fontWeight: '600' },
    sectionTitle: { paddingHorizontal: 12, paddingTop: 14, paddingBottom: 6, color: colors.muted, fontSize: 12, fontWeight: '600' },
    emptyText: { color: colors.muted, fontSize: 14, lineHeight: 22, paddingHorizontal: 12, paddingVertical: 20 },
    projectHeader: { minHeight: 44, flexDirection: 'row', alignItems: 'center', gap: 2, paddingHorizontal: 4 },
    projectMain: { minWidth: 0, flex: 1, minHeight: 44, flexDirection: 'row', alignItems: 'center', gap: 6, borderRadius: 12, paddingHorizontal: 4 },
    projectName: { minWidth: 0, flex: 1, color: colors.foreground, fontSize: 14, fontWeight: '600' },
    projectTime: { color: colors.subtle, fontSize: 11 },
    projectAction: { width: 44, height: 44, borderRadius: 12, alignItems: 'center', justifyContent: 'center' },
    sessionRow: { minHeight: 58, flexDirection: 'row', alignItems: 'center', borderRadius: 14, paddingLeft: 12, paddingRight: 4, paddingVertical: 6, gap: 10, marginVertical: 2 },
    projectSessionRow: { marginLeft: 20 },
    sessionRowSelected: { backgroundColor: colors.pressed },
    sessionCopy: { minWidth: 0, flex: 1 },
    moreButton: { width: 44, height: 44, borderRadius: 22, alignItems: 'center', justifyContent: 'center' },
    sessionTitleRow: { flexDirection: 'row', alignItems: 'center', gap: 5 },
    sessionTitle: { minWidth: 0, flex: 1, color: colors.foreground, fontSize: 15, fontWeight: '500' },
    time: { color: colors.subtle, fontSize: 11, lineHeight: 16 },
    preview: { color: colors.muted, fontSize: 12, lineHeight: 18, marginTop: 2 },
    foldButton: { minHeight: 44, justifyContent: 'center', borderRadius: 12, marginHorizontal: 4, paddingHorizontal: 12 },
    showMoreButton: { minHeight: 44, alignItems: 'center', justifyContent: 'center', borderRadius: 14, marginTop: 4 },
    foldText: { color: colors.muted, fontSize: 13, fontWeight: '500' },
    footer: { minHeight: 60, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderTopWidth: 1, borderTopColor: colors.border, paddingHorizontal: 16 },
    statusButton: { minHeight: 44, flexDirection: 'row', alignItems: 'center', gap: 7, paddingHorizontal: 8, borderRadius: 12 },
    statusLabel: { color: colors.muted, fontSize: 12 },
    statusDot: { width: 7, height: 7, borderRadius: 4, backgroundColor: '#C5A24A' },
    statusOpen: { backgroundColor: '#4FA86C' },
    statusOffline: { backgroundColor: '#C85B52' },
    actionOverlay: { position: 'absolute', inset: 0, justifyContent: 'flex-end' },
    actionBackdrop: { position: 'absolute', inset: 0, backgroundColor: 'rgba(10,18,24,0.32)' },
    actionSheet: { backgroundColor: colors.card, borderTopLeftRadius: 24, borderTopRightRadius: 24, paddingHorizontal: 16, paddingTop: 18, boxShadow: '0 -8px 30px rgba(0,0,0,0.12)' },
    actionTitle: { color: colors.muted, fontSize: 13, paddingHorizontal: 12, paddingBottom: 10 },
    sheetAction: { minHeight: 48, borderRadius: 12, flexDirection: 'row', alignItems: 'center', gap: 12, paddingHorizontal: 12 },
    sheetActionText: { fontSize: 15, fontWeight: '500' },
    renameOverlay: { position: 'absolute', inset: 0, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 22 },
    renameCard: { width: '100%', maxWidth: 420, borderRadius: 20, backgroundColor: colors.card, padding: 20, boxShadow: '0 14px 34px rgba(0,0,0,0.2)' },
    renameTitle: { color: colors.foreground, fontSize: 18, fontWeight: '600', marginBottom: 14 },
    renameInput: { height: 48, borderWidth: 1, borderColor: colors.border, borderRadius: 12, paddingHorizontal: 12, color: colors.foreground, fontSize: 15 },
    renameActions: { flexDirection: 'row', justifyContent: 'flex-end', gap: 9, marginTop: 15 },
    renameButton: { minWidth: 72, height: 44, borderRadius: 12, alignItems: 'center', justifyContent: 'center' },
    renamePrimary: { backgroundColor: '#208AEF' },
    renameCancelText: { color: colors.muted, fontSize: 14, fontWeight: '500' },
    renamePrimaryText: { color: '#FFFFFF', fontSize: 14, fontWeight: '600' },
  });
}

export type ConversationStyles = ReturnType<typeof createConversationStyles>;
