import { StyleSheet } from 'react-native';

export const sidebarStyles = StyleSheet.create({
  modalRoot: { flex: 1, flexDirection: 'row' },
  backdrop: { position: 'absolute', inset: 0, backgroundColor: 'rgba(16,16,14,0.28)' },
  drawer: {
    height: '100%',
    backgroundColor: '#F2F1EE',
    borderTopRightRadius: 18,
    borderBottomRightRadius: 18,
    paddingHorizontal: 10,
    boxShadow: '5px 0 18px rgba(0,0,0,0.18)',
  },
  brandRow: { height: 45, justifyContent: 'center', paddingHorizontal: 8 },
  logo: { width: 34, height: 34, borderRadius: 10 },
  actions: { gap: 2, marginTop: 2 },
  actionButton: {
    minHeight: 38,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 11,
    borderRadius: 20,
    paddingHorizontal: 13,
  },
  actionLabel: { color: '#3E3D39', fontSize: 13, fontWeight: '500' },
  actionButtonSelected: { backgroundColor: '#E3E1DC' },
  rowPressed: { backgroundColor: '#E6E4DF' },
  listContent: { paddingTop: 12, paddingBottom: 12 },
  projectsTitle: {
    paddingHorizontal: 12,
    paddingTop: 3,
    paddingBottom: 5,
    color: '#8A8984',
    fontSize: 11,
    fontWeight: '600',
  },
  sectionTitle: {
    paddingHorizontal: 12,
    paddingTop: 9,
    paddingBottom: 4,
    color: '#8A8984',
    fontSize: 11,
    fontWeight: '600',
  },
  emptyText: { color: '#8B8A86', fontSize: 12, lineHeight: 19, paddingHorizontal: 13, paddingVertical: 16 },
  projectHeader: {
    minHeight: 32,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 1,
    paddingHorizontal: 4,
  },
  projectMain: {
    minWidth: 0,
    flex: 1,
    minHeight: 30,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    borderRadius: 9,
    paddingHorizontal: 4,
  },
  projectName: { minWidth: 0, flex: 1, color: '#6F6D68', fontSize: 12, fontWeight: '600' },
  projectTime: { color: '#999792', fontSize: 10 },
  projectAction: { width: 26, height: 26, borderRadius: 7, alignItems: 'center', justifyContent: 'center' },
  sessionRow: {
    minHeight: 38,
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 11,
    paddingLeft: 10,
    paddingRight: 5,
    paddingVertical: 5,
    gap: 6,
  },
  projectSessionRow: { paddingLeft: 38 },
  sessionRowSelected: { backgroundColor: '#E3E1DC' },
  sessionCopy: { minWidth: 0, flex: 1 },
  moreButton: { width: 28, height: 28, borderRadius: 14, alignItems: 'center', justifyContent: 'center' },
  sessionTitleRow: { flexDirection: 'row', alignItems: 'center', gap: 5 },
  sessionTitle: { minWidth: 0, flex: 1, color: '#3B3A36', fontSize: 13, fontWeight: '500' },
  time: { color: '#999792', fontSize: 10, lineHeight: 14 },
  preview: { color: '#96948F', fontSize: 11, lineHeight: 15, marginTop: 1 },
  foldButton: { minHeight: 30, justifyContent: 'center', borderRadius: 11, marginHorizontal: 4, paddingHorizontal: 10 },
  showMoreButton: { minHeight: 34, alignItems: 'center', justifyContent: 'center', borderRadius: 17, marginTop: 4 },
  foldText: { color: '#8A8984', fontSize: 12, fontWeight: '500' },
  footer: {
    minHeight: 51,
    flexDirection: 'row',
    alignItems: 'center',
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: '#DFDDD8',
  },
  statusButton: { width: 40, height: 40, alignItems: 'center', justifyContent: 'center' },
  statusDot: { width: 8, height: 8, borderRadius: 4, backgroundColor: '#C5A24A' },
  statusOpen: { backgroundColor: '#4FA86C' },
  logoutTarget: { alignItems: 'center', paddingBottom: 2 },
  logoutHint: { color: '#ABA9A4', fontSize: 9 },
  actionOverlay: { position: 'absolute', inset: 0, justifyContent: 'flex-end' },
  actionBackdrop: { position: 'absolute', inset: 0, backgroundColor: 'rgba(16,16,14,0.28)' },
  actionSheet: {
    backgroundColor: '#FAF9F7',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    paddingHorizontal: 12,
    paddingTop: 14,
    boxShadow: '0 -8px 30px rgba(0,0,0,0.2)',
  },
  actionTitle: { color: '#777570', fontSize: 12, paddingHorizontal: 12, paddingBottom: 8 },
  sheetAction: { minHeight: 48, borderRadius: 12, flexDirection: 'row', alignItems: 'center', gap: 12, paddingHorizontal: 12 },
  sheetActionText: { fontSize: 15, fontWeight: '500' },
  renameOverlay: { position: 'absolute', inset: 0, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 22 },
  renameCard: { width: '100%', borderRadius: 17, backgroundColor: '#FFFFFF', padding: 17, boxShadow: '0 14px 34px rgba(0,0,0,0.25)' },
  renameTitle: { color: '#292824', fontSize: 17, fontWeight: '600', marginBottom: 14 },
  renameInput: { height: 44, borderWidth: StyleSheet.hairlineWidth, borderColor: '#D4D2CD', borderRadius: 11, paddingHorizontal: 12, color: '#292824', fontSize: 15 },
  renameActions: { flexDirection: 'row', justifyContent: 'flex-end', gap: 9, marginTop: 15 },
  renameButton: { minWidth: 72, height: 38, borderRadius: 10, alignItems: 'center', justifyContent: 'center' },
  renamePrimary: { backgroundColor: '#292824' },
  renameCancelText: { color: '#6F6D68', fontSize: 14, fontWeight: '500' },
  renamePrimaryText: { color: '#FFFFFF', fontSize: 14, fontWeight: '600' },
});
